package br.uern.sisgeq.util;
// Generated 23/11/2010 09:58:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Disciplina generated by hbm2java
 */
public class Disciplina  implements java.io.Serializable {


     private Integer id;
     private Departamento departamento;
     private String codigo;
     private String nome;
     private Set<Turma> turmas = new HashSet<Turma>(0);

    public Disciplina() {
    }

	
    public Disciplina(Departamento departamento, String codigo, String nome) {
        this.departamento = departamento;
        this.codigo = codigo;
        this.nome = nome;
    }
    public Disciplina(Departamento departamento, String codigo, String nome, Set<Turma> turmas) {
       this.departamento = departamento;
       this.codigo = codigo;
       this.nome = nome;
       this.turmas = turmas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Turma> getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set<Turma> turmas) {
        this.turmas = turmas;
    }




}


