package br.uern.sisgeq.util;
// Generated 23/11/2010 09:58:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private String matriculaCpf;
     private Departamento departamento;
     private Curso curso;
     private String nome;
     private String cidade;
     private String estado;
     private String naturalidade;
     private String nacionalidade;
     private Set<PessoaTurma> pessoaTurmas = new HashSet<PessoaTurma>(0);
     private Set<Perfil> perfils = new HashSet<Perfil>(0);
     private Set<PessoaQuestionario> pessoaQuestionarios = new HashSet<PessoaQuestionario>(0);

    public Pessoa() {
    }

	
    public Pessoa(String matriculaCpf, Departamento departamento, Curso curso, String nome) {
        this.matriculaCpf = matriculaCpf;
        this.departamento = departamento;
        this.curso = curso;
        this.nome = nome;
    }
    public Pessoa(String matriculaCpf, Departamento departamento, Curso curso, String nome, String cidade, String estado, String naturalidade, String nacionalidade, Set<PessoaTurma> pessoaTurmas, Set<Perfil> perfils, Set<PessoaQuestionario> pessoaQuestionarios) {
       this.matriculaCpf = matriculaCpf;
       this.departamento = departamento;
       this.curso = curso;
       this.nome = nome;
       this.cidade = cidade;
       this.estado = estado;
       this.naturalidade = naturalidade;
       this.nacionalidade = nacionalidade;
       this.pessoaTurmas = pessoaTurmas;
       this.perfils = perfils;
       this.pessoaQuestionarios = pessoaQuestionarios;
    }
   
    public String getMatriculaCpf() {
        return this.matriculaCpf;
    }
    
    public void setMatriculaCpf(String matriculaCpf) {
        this.matriculaCpf = matriculaCpf;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getNaturalidade() {
        return this.naturalidade;
    }
    
    public void setNaturalidade(String naturalidade) {
        this.naturalidade = naturalidade;
    }
    public String getNacionalidade() {
        return this.nacionalidade;
    }
    
    public void setNacionalidade(String nacionalidade) {
        this.nacionalidade = nacionalidade;
    }
    public Set<PessoaTurma> getPessoaTurmas() {
        return this.pessoaTurmas;
    }
    
    public void setPessoaTurmas(Set<PessoaTurma> pessoaTurmas) {
        this.pessoaTurmas = pessoaTurmas;
    }
    public Set<Perfil> getPerfils() {
        return this.perfils;
    }
    
    public void setPerfils(Set<Perfil> perfils) {
        this.perfils = perfils;
    }
    public Set<PessoaQuestionario> getPessoaQuestionarios() {
        return this.pessoaQuestionarios;
    }
    
    public void setPessoaQuestionarios(Set<PessoaQuestionario> pessoaQuestionarios) {
        this.pessoaQuestionarios = pessoaQuestionarios;
    }




}


