package br.uern.sisgeq.util;
// Generated 23/11/2010 09:58:27 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Questionario generated by hbm2java
 */
public class Questionario  implements java.io.Serializable {


     private Integer id;
     private Restricao restricao;
     private Date dataFim;
     private Date dataInicio;
     private String descricao;
     private Integer situacao;
     private Set<PessoaQuestionario> pessoaQuestionarios = new HashSet<PessoaQuestionario>(0);
     private Set<Pergunta> perguntas = new HashSet<Pergunta>(0);

    public Questionario() {
    }

	
    public Questionario(Restricao restricao, Date dataFim, Date dataInicio, String descricao) {
        this.restricao = restricao;
        this.dataFim = dataFim;
        this.dataInicio = dataInicio;
        this.descricao = descricao;
    }
    public Questionario(Restricao restricao, Date dataFim, Date dataInicio, String descricao, Integer situacao, Set<PessoaQuestionario> pessoaQuestionarios, Set<Pergunta> perguntas) {
       this.restricao = restricao;
       this.dataFim = dataFim;
       this.dataInicio = dataInicio;
       this.descricao = descricao;
       this.situacao = situacao;
       this.pessoaQuestionarios = pessoaQuestionarios;
       this.perguntas = perguntas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Restricao getRestricao() {
        return this.restricao;
    }
    
    public void setRestricao(Restricao restricao) {
        this.restricao = restricao;
    }
    public Date getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Integer getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Integer situacao) {
        this.situacao = situacao;
    }
    public Set<PessoaQuestionario> getPessoaQuestionarios() {
        return this.pessoaQuestionarios;
    }
    
    public void setPessoaQuestionarios(Set<PessoaQuestionario> pessoaQuestionarios) {
        this.pessoaQuestionarios = pessoaQuestionarios;
    }
    public Set<Pergunta> getPerguntas() {
        return this.perguntas;
    }
    
    public void setPerguntas(Set<Pergunta> perguntas) {
        this.perguntas = perguntas;
    }




}


