package br.uern.sisgeq.model;
// Generated 23/11/2010 09:58:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private Integer id;
     private Nucleo nucleo;
     private String area;
     private String nome;
     private Set<Pessoa> pessoas = new HashSet<Pessoa>(0);
     private Set<Curso> cursos = new HashSet<Curso>(0);
     private Set<Disciplina> disciplinas = new HashSet<Disciplina>(0);

    public Departamento() {
    }

	
    public Departamento(Nucleo nucleo) {
        this.nucleo = nucleo;
    }
    public Departamento(Nucleo nucleo, String area, String nome, Set<Pessoa> pessoas, Set<Curso> cursos, Set<Disciplina> disciplinas) {
       this.nucleo = nucleo;
       this.area = area;
       this.nome = nome;
       this.pessoas = pessoas;
       this.cursos = cursos;
       this.disciplinas = disciplinas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Nucleo getNucleo() {
        return this.nucleo;
    }
    
    public void setNucleo(Nucleo nucleo) {
        this.nucleo = nucleo;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Pessoa> getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set<Pessoa> pessoas) {
        this.pessoas = pessoas;
    }
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }
    public Set<Disciplina> getDisciplinas() {
        return this.disciplinas;
    }
    
    public void setDisciplinas(Set<Disciplina> disciplinas) {
        this.disciplinas = disciplinas;
    }




}


