package br.uern.sisgeq.model;
// Generated 23/11/2010 09:58:27 by Hibernate Tools 3.2.1.GA



/**
 * PessoaQuestionario generated by hbm2java
 */
public class PessoaQuestionario  implements java.io.Serializable {


     private PessoaQuestionarioId id;
     private Questionario questionario;
     private Pessoa pessoa;
     private Integer situacao;

    public PessoaQuestionario() {
    }

	
    public PessoaQuestionario(PessoaQuestionarioId id, Questionario questionario, Pessoa pessoa) {
        this.id = id;
        this.questionario = questionario;
        this.pessoa = pessoa;
    }
    public PessoaQuestionario(PessoaQuestionarioId id, Questionario questionario, Pessoa pessoa, Integer situacao) {
       this.id = id;
       this.questionario = questionario;
       this.pessoa = pessoa;
       this.situacao = situacao;
    }
   
    public PessoaQuestionarioId getId() {
        return this.id;
    }
    
    public void setId(PessoaQuestionarioId id) {
        this.id = id;
    }
    public Questionario getQuestionario() {
        return this.questionario;
    }
    
    public void setQuestionario(Questionario questionario) {
        this.questionario = questionario;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Integer getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Integer situacao) {
        this.situacao = situacao;
    }




}


