package br.uern.sisgeq.model;
// Generated 23/11/2010 09:58:27 by Hibernate Tools 3.2.1.GA



/**
 * PessoaTurma generated by hbm2java
 */
public class PessoaTurma  implements java.io.Serializable {


     private PessoaTurmaId id;
     private Turma turma;
     private Pessoa pessoa;
     private Integer situacao;
     private Float media;

    public PessoaTurma() {
    }

	
    public PessoaTurma(PessoaTurmaId id, Turma turma, Pessoa pessoa) {
        this.id = id;
        this.turma = turma;
        this.pessoa = pessoa;
    }
    public PessoaTurma(PessoaTurmaId id, Turma turma, Pessoa pessoa, Integer situacao, Float media) {
       this.id = id;
       this.turma = turma;
       this.pessoa = pessoa;
       this.situacao = situacao;
       this.media = media;
    }
   
    public PessoaTurmaId getId() {
        return this.id;
    }
    
    public void setId(PessoaTurmaId id) {
        this.id = id;
    }
    public Turma getTurma() {
        return this.turma;
    }
    
    public void setTurma(Turma turma) {
        this.turma = turma;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Integer getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Integer situacao) {
        this.situacao = situacao;
    }
    public Float getMedia() {
        return this.media;
    }
    
    public void setMedia(Float media) {
        this.media = media;
    }




}


