package br.uern.sisgeq.model;
// Generated 23/11/2010 09:58:27 by Hibernate Tools 3.2.1.GA



/**
 * Resposta generated by hbm2java
 */
public class Resposta  implements java.io.Serializable {


     private Integer id;
     private Pergunta pergunta;
     private String descricao;

    public Resposta() {
    }

    public Resposta(Pergunta pergunta, String descricao) {
       this.pergunta = pergunta;
       this.descricao = descricao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pergunta getPergunta() {
        return this.pergunta;
    }
    
    public void setPergunta(Pergunta pergunta) {
        this.pergunta = pergunta;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


