package br.uern.sisgeq.util;
// Generated 23/11/2010 09:58:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Nucleo generated by hbm2java
 */
public class Nucleo  implements java.io.Serializable {


     private int id;
     private Campus campus;
     private String nome;
     private Set<Departamento> departamentos = new HashSet<Departamento>(0);
     private Set<Turma> turmas = new HashSet<Turma>(0);

    public Nucleo() {
    }

	
    public Nucleo(int id, Campus campus) {
        this.id = id;
        this.campus = campus;
    }
    public Nucleo(int id, Campus campus, String nome, Set<Departamento> departamentos, Set<Turma> turmas) {
       this.id = id;
       this.campus = campus;
       this.nome = nome;
       this.departamentos = departamentos;
       this.turmas = turmas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Campus getCampus() {
        return this.campus;
    }
    
    public void setCampus(Campus campus) {
        this.campus = campus;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Departamento> getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set<Departamento> departamentos) {
        this.departamentos = departamentos;
    }
    public Set<Turma> getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set<Turma> turmas) {
        this.turmas = turmas;
    }




}


