package br.uern.sisgeq.util;
// Generated 23/11/2010 09:58:27 by Hibernate Tools 3.2.1.GA



/**
 * PessoaQuestionarioId generated by hbm2java
 */
public class PessoaQuestionarioId  implements java.io.Serializable {


     private String pessoaMatriculaCpf;
     private int questionarioId;

    public PessoaQuestionarioId() {
    }

    public PessoaQuestionarioId(String pessoaMatriculaCpf, int questionarioId) {
       this.pessoaMatriculaCpf = pessoaMatriculaCpf;
       this.questionarioId = questionarioId;
    }
   
    public String getPessoaMatriculaCpf() {
        return this.pessoaMatriculaCpf;
    }
    
    public void setPessoaMatriculaCpf(String pessoaMatriculaCpf) {
        this.pessoaMatriculaCpf = pessoaMatriculaCpf;
    }
    public int getQuestionarioId() {
        return this.questionarioId;
    }
    
    public void setQuestionarioId(int questionarioId) {
        this.questionarioId = questionarioId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PessoaQuestionarioId) ) return false;
		 PessoaQuestionarioId castOther = ( PessoaQuestionarioId ) other; 
         
		 return ( (this.getPessoaMatriculaCpf()==castOther.getPessoaMatriculaCpf()) || ( this.getPessoaMatriculaCpf()!=null && castOther.getPessoaMatriculaCpf()!=null && this.getPessoaMatriculaCpf().equals(castOther.getPessoaMatriculaCpf()) ) )
 && (this.getQuestionarioId()==castOther.getQuestionarioId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPessoaMatriculaCpf() == null ? 0 : this.getPessoaMatriculaCpf().hashCode() );
         result = 37 * result + this.getQuestionarioId();
         return result;
   }   


}


