package br.uern.sisgeq.util;
// Generated 23/11/2010 09:58:27 by Hibernate Tools 3.2.1.GA



/**
 * PessoaTurmaId generated by hbm2java
 */
public class PessoaTurmaId  implements java.io.Serializable {


     private String pessoaMatriculaCpf;
     private int turmaId;

    public PessoaTurmaId() {
    }

    public PessoaTurmaId(String pessoaMatriculaCpf, int turmaId) {
       this.pessoaMatriculaCpf = pessoaMatriculaCpf;
       this.turmaId = turmaId;
    }
   
    public String getPessoaMatriculaCpf() {
        return this.pessoaMatriculaCpf;
    }
    
    public void setPessoaMatriculaCpf(String pessoaMatriculaCpf) {
        this.pessoaMatriculaCpf = pessoaMatriculaCpf;
    }
    public int getTurmaId() {
        return this.turmaId;
    }
    
    public void setTurmaId(int turmaId) {
        this.turmaId = turmaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PessoaTurmaId) ) return false;
		 PessoaTurmaId castOther = ( PessoaTurmaId ) other; 
         
		 return ( (this.getPessoaMatriculaCpf()==castOther.getPessoaMatriculaCpf()) || ( this.getPessoaMatriculaCpf()!=null && castOther.getPessoaMatriculaCpf()!=null && this.getPessoaMatriculaCpf().equals(castOther.getPessoaMatriculaCpf()) ) )
 && (this.getTurmaId()==castOther.getTurmaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPessoaMatriculaCpf() == null ? 0 : this.getPessoaMatriculaCpf().hashCode() );
         result = 37 * result + this.getTurmaId();
         return result;
   }   


}


