package br.uern.sisgeq.model;
// Generated 23/11/2010 09:58:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Campus generated by hbm2java
 */
public class Campus  implements java.io.Serializable {


     private int id;
     private String nome;
     private Set<Nucleo> nucleos = new HashSet<Nucleo>(0);

    public Campus() {
    }

	
    public Campus(int id) {
        this.id = id;
    }
    public Campus(int id, String nome, Set<Nucleo> nucleos) {
       this.id = id;
       this.nome = nome;
       this.nucleos = nucleos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Nucleo> getNucleos() {
        return this.nucleos;
    }
    
    public void setNucleos(Set<Nucleo> nucleos) {
        this.nucleos = nucleos;
    }




}


