package br.uern.sisgeq.model;
// Generated 23/11/2010 09:58:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer id;
     private Departamento departamento;
     private String nome;
     private Set<Pessoa> pessoas = new HashSet<Pessoa>(0);

    public Curso() {
    }

	
    public Curso(Departamento departamento, String nome) {
        this.departamento = departamento;
        this.nome = nome;
    }
    public Curso(Departamento departamento, String nome, Set<Pessoa> pessoas) {
       this.departamento = departamento;
       this.nome = nome;
       this.pessoas = pessoas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Pessoa> getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set<Pessoa> pessoas) {
        this.pessoas = pessoas;
    }




}


