package br.uern.sisgeq.model;
// Generated 23/11/2010 09:58:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Pergunta generated by hbm2java
 */
public class Pergunta  implements java.io.Serializable {


     private Integer id;
     private Questionario questionario;
     private String descricao;
     private int numero;
     private Boolean obrigatoriedade;
     private Set<Alternativa> alternativas = new HashSet<Alternativa>(0);
     private Set<Resposta> respostas = new HashSet<Resposta>(0);

    public Pergunta() {
    }

	
    public Pergunta(Questionario questionario, String descricao, int numero) {
        this.questionario = questionario;
        this.descricao = descricao;
        this.numero = numero;
    }
    public Pergunta(Questionario questionario, String descricao, int numero, Boolean obrigatoriedade, Set<Alternativa> alternativas, Set<Resposta> respostas) {
       this.questionario = questionario;
       this.descricao = descricao;
       this.numero = numero;
       this.obrigatoriedade = obrigatoriedade;
       this.alternativas = alternativas;
       this.respostas = respostas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Questionario getQuestionario() {
        return this.questionario;
    }
    
    public void setQuestionario(Questionario questionario) {
        this.questionario = questionario;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Boolean getObrigatoriedade() {
        return this.obrigatoriedade;
    }
    
    public void setObrigatoriedade(Boolean obrigatoriedade) {
        this.obrigatoriedade = obrigatoriedade;
    }
    public Set<Alternativa> getAlternativas() {
        return this.alternativas;
    }
    
    public void setAlternativas(Set<Alternativa> alternativas) {
        this.alternativas = alternativas;
    }
    public Set<Resposta> getRespostas() {
        return this.respostas;
    }
    
    public void setRespostas(Set<Resposta> respostas) {
        this.respostas = respostas;
    }




}


